const canvas=document.getElementById('wheelCanvas'),ctx=canvas.getContext('2d');
const optionsList=document.getElementById('optionsList'),countBadge=document.getElementById('countBadge');
const result=document.getElementById('result');
let options=['Option 1','Option 2','Option 3','Option 4','Option 5','Option 6','Option 7','Option 8'];
let palette='bright',showLabels=true,showConfetti=true,sound=true,duration=5,rotation=0,spinning=false;
const palettes={bright:['#4f73ef','#ff5b52','#ffcc35','#39bb8a','#8457e8','#ff8c39','#23b9bf','#fa4f88'],pastel:['#9fb7ff','#ffaaa6','#ffe79a','#9fe0c4','#c8b1f4','#ffc38f','#9edee0','#ffafd0'],ocean:['#3264d6','#248bb2','#21a6a2','#27c58e','#5b82e9','#3c9ad4','#2759a7','#50c5c0'],sunset:['#f04d59','#f57a45','#f8b83c','#e8d35a','#ad5ae5','#7659d8','#dc4b91','#ff7b69'],mono:['#26364f','#43536c','#61718a','#7f8da3','#9ba7b7','#b5bec9','#cdd3db','#e3e6eb']};
function renderInputs(){optionsList.innerHTML='';options.forEach((value,i)=>{const row=document.createElement('div');row.className='option-row';row.innerHTML=`<input aria-label="Option ${i+1}" value="${escapeHtml(value)}" maxlength="40"><button class="delete-option" title="Remove option" aria-label="Remove option">♜</button>`;const input=row.querySelector('input');input.addEventListener('input',e=>{options[i]=e.target.value||`Option ${i+1}`;draw()});row.querySelector('button').addEventListener('click',()=>{if(options.length<=2)return;options.splice(i,1);renderInputs();draw()});optionsList.appendChild(row)});countBadge.textContent=options.length}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function draw(){const d=devicePixelRatio||1,rect=canvas.getBoundingClientRect();const size=720;canvas.width=size*d;canvas.height=size*d;ctx.setTransform(d,0,0,d,0,0);const cx=360,cy=360,r=345;ctx.clearRect(0,0,size,size);const colors=palettes[palette],n=options.length,step=Math.PI*2/n;ctx.save();ctx.translate(cx,cy);ctx.rotate(rotation*Math.PI/180);for(let i=0;i<n;i++){const a=-Math.PI/2+i*step;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,a,a+step);ctx.closePath();ctx.fillStyle=colors[i%colors.length];ctx.fill();ctx.lineWidth=2;ctx.strokeStyle='rgba(255,255,255,.85)';ctx.stroke();if(showLabels){ctx.save();ctx.rotate(a+step/2);ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=palette==='mono'&&i>5?'#20304a':'#fff';ctx.font=`800 ${Math.max(14,Math.min(23,31-n*1.25))}px Inter,system-ui,sans-serif`;let label=options[i]||`Option ${i+1}`;if(label.length>18)label=label.slice(0,17)+'…';ctx.fillText(label,r*.61,0);ctx.restore()}}ctx.restore();ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.lineWidth=3;ctx.strokeStyle='rgba(255,255,255,.95)';ctx.stroke()}
function spin(){if(spinning||options.length<2)return;spinning=true;document.body.classList.add('spinning');result.textContent='Spinning…';const n=options.length;const winner=Math.floor(Math.random()*n);const step=360/n;const targetCenter=winner*step+step/2;const current=((rotation%360)+360)%360;let delta=(360-targetCenter-current+360)%360;delta+=360*(5+Math.floor(Math.random()*3));const start=rotation,end=rotation+delta;const startTime=performance.now(),ms=duration*1000;playTick(0);function frame(now){const t=Math.min(1,(now-startTime)/ms),ease=1-Math.pow(1-t,4);rotation=start+(end-start)*ease;draw();if(t<1){if(sound&&Math.random()<.12)playTick(t);requestAnimationFrame(frame)}else{rotation=end%360;spinning=false;document.body.classList.remove('spinning');const win=options[winner];result.textContent=`🎉 ${win}`;if(sound)playWin();if(showConfetti)confetti()}}requestAnimationFrame(frame)}
function playTick(){if(!sound)return;try{const AC=window.AudioContext||window.webkitAudioContext;if(!window._ac)window._ac=new AC();const o=window._ac.createOscillator(),g=window._ac.createGain();o.frequency.value=560;o.type='sine';g.gain.setValueAtTime(.0001,window._ac.currentTime);g.gain.exponentialRampToValueAtTime(.045,window._ac.currentTime+.008);g.gain.exponentialRampToValueAtTime(.0001,window._ac.currentTime+.05);o.connect(g).connect(window._ac.destination);o.start();o.stop(window._ac.currentTime+.06)}catch(e){}}
function playWin(){try{const AC=window.AudioContext||window.webkitAudioContext;if(!window._ac)window._ac=new AC();[660,880,1047].forEach((f,i)=>{const o=window._ac.createOscillator(),g=window._ac.createGain();o.frequency.value=f;o.type='sine';g.gain.setValueAtTime(.0001,window._ac.currentTime+i*.09);g.gain.exponentialRampToValueAtTime(.07,window._ac.currentTime+i*.09+.02);g.gain.exponentialRampToValueAtTime(.0001,window._ac.currentTime+i*.09+.18);o.connect(g).connect(window._ac.destination);o.start(window._ac.currentTime+i*.09);o.stop(window._ac.currentTime+i*.09+.2)})}catch(e){}}
function confetti(){const c=document.getElementById('confetti'),x=c.getContext('2d');c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;x.scale(devicePixelRatio,devicePixelRatio);const pieces=Array.from({length:150},()=>({x:innerWidth/2+(Math.random()-.5)*180,y:innerHeight*.25+(Math.random()-.5)*60,vx:(Math.random()-.5)*8,vy:-Math.random()*9-3,s:Math.random()*8+4,r:Math.random()*Math.PI,c:palettes[palette][Math.floor(Math.random()*palettes[palette].length)]}));let t=0;function f(){x.clearRect(0,0,innerWidth,innerHeight);pieces.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.22;p.r+=.15;x.save();x.translate(p.x,p.y);x.rotate(p.r);x.fillStyle=p.c;x.fillRect(-p.s/2,-p.s/2,p.s,p.s*.55);x.restore()});if(++t<150)requestAnimationFrame(f);else x.clearRect(0,0,innerWidth,innerHeight)}f()}
function setToggle(btn,key){btn.classList.toggle('on');const on=btn.classList.contains('on');btn.setAttribute('aria-pressed',on);if(key==='labels')showLabels=on;if(key==='confetti')showConfetti=on;if(key==='sound')sound=on;draw()}
const templates={lunch:['Pizza','Burger','Sushi','Tacos','Pasta','Indian','Salad','Surprise'],names:['Alex','Sam','Jordan','Taylor','Riley','Casey','Morgan','Jamie'],yesno:['Yes','No','Maybe'],party:['Dance','Charades','Karaoke','Trivia','Truth or Dare','Pictionary','Freeze Dance','Surprise']};
document.getElementById('addOption').onclick=()=>{options.push(`Option ${options.length+1}`);renderInputs();draw();optionsList.lastElementChild?.querySelector('input')?.focus()};document.getElementById('shuffleOptions').onclick=()=>{for(let i=options.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[options[i],options[j]]=[options[j],options[i]]}renderInputs();draw()};document.getElementById('clearOptions').onclick=()=>{options=['Option 1','Option 2'];renderInputs();draw()};document.getElementById('spinButton').onclick=spin;document.getElementById('spinCenter').onclick=spin;document.getElementById('spinSettings').onclick=spin;document.getElementById('palette').onchange=e=>{palette=e.target.value;draw()};document.getElementById('duration').oninput=e=>{duration=+e.target.value;document.getElementById('durationValue').textContent=duration+'s'};document.querySelectorAll('.toggle').forEach(b=>b.onclick=()=>setToggle(b,b.dataset.setting));document.querySelectorAll('.template-card').forEach(b=>b.onclick=()=>{options=[...templates[b.dataset.template]];renderInputs();draw();document.getElementById('wheel').scrollIntoView({behavior:'smooth',block:'center'})});document.getElementById('resetBtn').onclick=()=>{options=['Option 1','Option 2','Option 3','Option 4','Option 5','Option 6','Option 7','Option 8'];palette='bright';showLabels=showConfetti=sound=true;duration=5;rotation=0;document.getElementById('palette').value='bright';document.getElementById('duration').value=5;document.getElementById('durationValue').textContent='5s';document.querySelectorAll('.toggle').forEach(b=>{b.classList.add('on');b.setAttribute('aria-pressed','true')});result.textContent='Ready when you are!';renderInputs();draw()};document.getElementById('themeBtn').onclick=()=>{document.body.classList.toggle('dark');document.getElementById('themeBtn').textContent=document.body.classList.contains('dark')?'☀':'☾'};document.getElementById('year').textContent=new Date().getFullYear();window.addEventListener('resize',draw);renderInputs();draw();
