(function(){
const data=window.WHEEL_CONFIG||{};const canvas=document.getElementById('wheelCanvas');if(!canvas)return;
const ctx=canvas.getContext('2d'),list=document.getElementById('optionsList'),badge=document.getElementById('countBadge'),result=document.getElementById('result');
let options=[...(data.options||['Option 1','Option 2','Option 3','Option 4','Option 5','Option 6','Option 7','Option 8'])],palette='bright',labels=true,confettiOn=true,sound=true,duration=5,rotation=0,spinning=false;
const defaults=[...(data.options||[])];
const palettes={bright:['#4f73ef','#ff5b52','#ffcc35','#39bb8a','#8457e8','#ff8c39','#23b9bf','#fa4f88'],pastel:['#9fb7ff','#ffaaa6','#ffe79a','#9fe0c4','#c8b1f4','#ffc38f','#9edee0','#ffafd0'],ocean:['#3264d6','#248bb2','#21a6a2','#27c58e','#5b82e9','#3c9ad4','#2759a7','#50c5c0'],sunset:['#f04d59','#f57a45','#f8b83c','#e8d35a','#ad5ae5','#7659d8','#dc4b91','#ff7b69'],mono:['#26364f','#43536c','#61718a','#7f8da3','#9ba7b7','#b5bec9','#cdd3db','#e3e6eb']};
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function inputs(){if(!list)return;list.innerHTML='';options.forEach((v,i)=>{const row=document.createElement('div');row.className='option-row';row.innerHTML=`<input value="${esc(v)}" maxlength="40" aria-label="Option ${i+1}"><button class="delete-option" aria-label="Remove option">×</button>`;row.querySelector('input').oninput=e=>{options[i]=e.target.value||`Option ${i+1}`;draw()};row.querySelector('button').onclick=()=>{if(options.length>2){options.splice(i,1);inputs();draw()}};list.appendChild(row)});if(badge)badge.textContent=options.length}
function draw(){const d=window.devicePixelRatio||1,size=720;canvas.width=size*d;canvas.height=size*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,size,size);const n=Math.max(options.length,2),step=Math.PI*2/n,r=345;ctx.save();ctx.translate(360,360);ctx.rotate(rotation*Math.PI/180);for(let i=0;i<n;i++){const a=-Math.PI/2+i*step;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,r,a,a+step);ctx.closePath();ctx.fillStyle=palettes[palette][i%8];ctx.fill();ctx.strokeStyle='rgba(255,255,255,.92)';ctx.lineWidth=2;ctx.stroke();if(labels){ctx.save();ctx.rotate(a+step/2);ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=palette==='mono'&&i>5?'#20304a':'#fff';ctx.font=`800 ${Math.max(13,Math.min(23,31-n*1.2))}px system-ui,sans-serif`;let t=options[i]||`Option ${i+1}`;if(t.length>18)t=t.slice(0,17)+'…';ctx.fillText(t,r*.61,0);ctx.restore()}}ctx.restore();ctx.beginPath();ctx.arc(360,360,r,0,Math.PI*2);ctx.strokeStyle='rgba(255,255,255,.95)';ctx.lineWidth=3;ctx.stroke()}
function audioTone(freq,dur=.06,vol=.04){if(!sound)return;try{const A=window.AudioContext||window.webkitAudioContext;if(!window._a)window._a=new A();const o=window._a.createOscillator(),g=window._a.createGain(),t=window._a.currentTime;o.frequency.value=freq;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g).connect(window._a.destination);o.start(t);o.stop(t+dur+.01)}catch(e){}}
function winSound(){[660,880,1047].forEach((f,i)=>setTimeout(()=>audioTone(f,.18,.07),i*90))}
function confetti(){if(!confettiOn)return;const c=document.getElementById('confetti');if(!c)return;const x=c.getContext('2d');c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);const p=Array.from({length:130},()=>({x:innerWidth/2+(Math.random()-.5)*220,y:innerHeight*.25,vx:(Math.random()-.5)*8,vy:-Math.random()*8-3,s:Math.random()*8+4,r:Math.random()*6,c:palettes[palette][Math.floor(Math.random()*8)]}));let t=0;function f(){x.clearRect(0,0,innerWidth,innerHeight);p.forEach(a=>{a.x+=a.vx;a.y+=a.vy;a.vy+=.2;a.r+=.15;x.save();x.translate(a.x,a.y);x.rotate(a.r);x.fillStyle=a.c;x.fillRect(-a.s/2,-a.s/2,a.s,a.s*.55);x.restore()});if(++t<140)requestAnimationFrame(f);else x.clearRect(0,0,innerWidth,innerHeight)}f()}
function spin(){if(spinning||options.length<2)return;spinning=true;result.textContent='Spinning…';const n=options.length,w=Math.floor(Math.random()*n),step=360/n,target=w*step+step/2,current=((rotation%360)+360)%360,delta=(360-target-current+360)%360+360*(5+Math.floor(Math.random()*3)),start=rotation,end=rotation+delta,st=performance.now();function f(now){const t=Math.min(1,(now-st)/(duration*1000)),e=1-Math.pow(1-t,4);rotation=start+(end-start)*e;draw();if(t<1){if(sound&&Math.random()<.12)audioTone(560);requestAnimationFrame(f)}else{rotation=end%360;spinning=false;result.textContent='🎉 '+(options[w]||`Option ${w+1}`);winSound();confetti()}}requestAnimationFrame(f)}
function reset(){options=defaults.length?[...defaults]:['Option 1','Option 2','Option 3','Option 4','Option 5','Option 6','Option 7','Option 8'];rotation=0;palette='bright';duration=5;labels=confettiOn=sound=true;document.getElementById('palette').value='bright';document.getElementById('duration').value=5;document.getElementById('durationValue').textContent='5s';document.querySelectorAll('.toggle').forEach(b=>{b.classList.add('on');b.setAttribute('aria-pressed','true')});result.textContent='Ready when you are!';inputs();draw()}
['spinButton','spinCenter','spinSettings'].forEach(id=>{const el=document.getElementById(id);if(el)el.onclick=spin});const add=document.getElementById('addOption');if(add)add.onclick=()=>{options.push(`Option ${options.length+1}`);inputs();draw();list?.lastElementChild?.querySelector('input')?.focus()};const shuffle=()=>{for(let i=options.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[options[i],options[j]]=[options[j],options[i]]}inputs();draw()};const sh=document.getElementById('shuffleOptions');if(sh)sh.onclick=shuffle;const wh=document.getElementById('wheelShuffle');if(wh)wh.onclick=shuffle;const clear=document.getElementById('clearOptions');if(clear)clear.onclick=()=>{options=['Option 1','Option 2'];inputs();draw()};const pal=document.getElementById('palette');if(pal)pal.onchange=e=>{palette=e.target.value;draw()};const dur=document.getElementById('duration');if(dur)dur.oninput=e=>{duration=+e.target.value;document.getElementById('durationValue').textContent=duration+'s'};document.querySelectorAll('.toggle').forEach(b=>b.onclick=()=>{b.classList.toggle('on');const on=b.classList.contains('on');b.setAttribute('aria-pressed',on);if(b.dataset.setting==='labels')labels=on;if(b.dataset.setting==='confetti')confettiOn=on;if(b.dataset.setting==='sound')sound=on;draw()});const resetBtn=document.getElementById('resetBtn');if(resetBtn)resetBtn.onclick=reset;const theme=document.getElementById('themeBtn');if(theme)theme.onclick=()=>{document.body.classList.toggle('dark');theme.textContent=document.body.classList.contains('dark')?'☀':'☾'};const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();window.addEventListener('resize',draw);inputs();draw();
})();
